FROM toposoid/toposoid-scala-lib-base:0.6

WORKDIR /app
ARG TARGET_BRANCH
ENV DEPLOYMENT=local

RUN git clone https://github.com/toposoid/data-accessor-redis-web.git \
&& cd data-accessor-redis-web \
&& git fetch origin ${TARGET_BRANCH} \
&& git checkout ${TARGET_BRANCH}
